import { Word } from "../word";
import { AppState } from "./appState";

type OPEN_SIDE_MANU = "OPEN_SIDE_MANU";
type CLOSE_SIDE_MANU = "CLOSE_SIDE_MANU";
type CLOSE_WORD_DIALOG = "CLOSE_WORD_DIALOG";
type CREATE_NEW_WORD = "CREATE_NEW_WORD";
type UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
type OPEN_NEW_WORD_DIALOG = "OPEN_NEW_WORD_DIALOG";
type OPEN_UPDATE_WORD_DIALOG = "OPEN_UPDATE_WORD_DIALOG";
type UPDATE_WORD_ITEM = "UPDATE_WORD_ITEM";
type FILTER_MAIN_SECTION_LIST = "FILTER_MAIN_SECTION_LIST";
type UPDATE_MULTIPLE = "UPDATE_MULTIPLE";

type actionType = {
  OPEN_SIDE_MANU: OPEN_SIDE_MANU;
  CLOSE_SIDE_MANU: CLOSE_SIDE_MANU;
  CLOSE_WORD_DIALOG: CLOSE_WORD_DIALOG;
  CREATE_NEW_WORD: CREATE_NEW_WORD;
  UPDATE_CATEGORIES: UPDATE_CATEGORIES;
  OPEN_NEW_WORD_DIALOG: OPEN_NEW_WORD_DIALOG;
  OPEN_UPDATE_WORD_DIALOG: OPEN_UPDATE_WORD_DIALOG;
  UPDATE_WORD_ITEM: UPDATE_WORD_ITEM;
  FILTER_MAIN_SECTION_LIST: FILTER_MAIN_SECTION_LIST;
  UPDATE_MULTIPLE: UPDATE_MULTIPLE;
};

export const AppActionType: actionType = {
  OPEN_SIDE_MANU: "OPEN_SIDE_MANU",
  CLOSE_SIDE_MANU: "CLOSE_SIDE_MANU",
  CLOSE_WORD_DIALOG: "CLOSE_WORD_DIALOG",
  CREATE_NEW_WORD: "CREATE_NEW_WORD",
  UPDATE_CATEGORIES: "UPDATE_CATEGORIES",
  OPEN_NEW_WORD_DIALOG: "OPEN_NEW_WORD_DIALOG",
  OPEN_UPDATE_WORD_DIALOG: "OPEN_UPDATE_WORD_DIALOG",
  UPDATE_WORD_ITEM: "UPDATE_WORD_ITEM",
  FILTER_MAIN_SECTION_LIST: "FILTER_MAIN_SECTION_LIST",
  UPDATE_MULTIPLE: "UPDATE_MULTIPLE",
};

export type AppAction =
  | { type: OPEN_SIDE_MANU }
  | { type: CLOSE_SIDE_MANU }
  | { type: OPEN_NEW_WORD_DIALOG }
  | { type: OPEN_UPDATE_WORD_DIALOG; payload: Word }
  | { type: CLOSE_WORD_DIALOG }
  | { type: CREATE_NEW_WORD; payload: Word }
  | { type: UPDATE_WORD_ITEM; payload: Word }
  | { type: UPDATE_CATEGORIES }
  | { type: FILTER_MAIN_SECTION_LIST; payload: string }
  | { type: UPDATE_MULTIPLE; payload: AppState };
