import { Word } from "../../types";

type CREATE_NEW_WORD = "CREATE_NEW_WORD";
type UPDATE_WORD_ITEM = "UPDATE_WORD_ITEM";
type FILTER_MAIN_SECTION_LIST = "FILTER_MAIN_SECTION_LIST";
type UPDATE_WORD_DATA = "UPDATE_WORD_DATA";
type LOGIN = "LOGIN";
type DELETE_WORD_ITEM = "DELETE_WORD_ITEM";
type LOGOUT = "LOGOUT";

type STORE_WORDS = "STORE_WORDS";
type STORE_USER_ID = "STORE_USER_ID";

type actionType = {
  CREATE_NEW_WORD: CREATE_NEW_WORD;
  UPDATE_WORD_ITEM: UPDATE_WORD_ITEM;
  FILTER_MAIN_SECTION_LIST: FILTER_MAIN_SECTION_LIST;
  UPDATE_WORD_DATA: UPDATE_WORD_DATA;
  LOGIN: LOGIN;
  DELETE_WORD_ITEM: DELETE_WORD_ITEM;
  LOGOUT: LOGOUT;

  STORE_WORDS: STORE_WORDS;
  STORE_USER_ID: STORE_USER_ID;
};

export const AppActions: actionType = {
  CREATE_NEW_WORD: "CREATE_NEW_WORD",
  UPDATE_WORD_ITEM: "UPDATE_WORD_ITEM",
  FILTER_MAIN_SECTION_LIST: "FILTER_MAIN_SECTION_LIST",
  UPDATE_WORD_DATA: "UPDATE_WORD_DATA",
  LOGIN: "LOGIN",
  DELETE_WORD_ITEM: "DELETE_WORD_ITEM",
  LOGOUT: "LOGOUT",

  STORE_WORDS: "STORE_WORDS",
  STORE_USER_ID: "STORE_USER_ID",
};

export type AppAction =
  | { type: CREATE_NEW_WORD; payload: Word }
  | { type: UPDATE_WORD_ITEM; payload: Word }
  | { type: FILTER_MAIN_SECTION_LIST; payload: string }
  | { type: UPDATE_WORD_DATA; payload: Word[] }
  | { type: LOGIN }
  | { type: DELETE_WORD_ITEM; payload: Word }
  | { type: LOGOUT }
  | { type: STORE_WORDS; payload: Word[] }
  | { type: STORE_USER_ID; payload: string };
