import { Word } from "../word";

type OPEN_SIDE_MENU = "OPEN_SIDE_MENU";
type CLOSE_SIDE_MENU = "CLOSE_SIDE_MENU";
type UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
type SET_CURRENT_CATGORIE = "SET_CURRENT_CATGORIE";

type actionType = {
  OPEN_SIDE_MENU: OPEN_SIDE_MENU;
  CLOSE_SIDE_MENU: CLOSE_SIDE_MENU;
  UPDATE_CATEGORIES: UPDATE_CATEGORIES;
  SET_CURRENT_CATGORIE: SET_CURRENT_CATGORIE;
};

export const NavActions: actionType = {
  OPEN_SIDE_MENU: "OPEN_SIDE_MENU",
  CLOSE_SIDE_MENU: "CLOSE_SIDE_MENU",
  UPDATE_CATEGORIES: "UPDATE_CATEGORIES",
  SET_CURRENT_CATGORIE: "SET_CURRENT_CATGORIE",
};

export type NavAction =
  | { type: OPEN_SIDE_MENU }
  | { type: CLOSE_SIDE_MENU }
  | { type: UPDATE_CATEGORIES; payload: Word[] }
  | { type: SET_CURRENT_CATGORIE; payload: string };
