export const dummyData = [
  {
    _id: 1,
    text: "word1",
    notes: "note",
    // orginal url: "url",
    categories: ["Inbox"],
    status: "active",
  },
  {
    _id: 2,
    text: "word2",
    notes: "note",
    // orginal url: "url",
    categories: ["New Words"],
    status: "active",
  },
  {
    _id: 3,
    text: "word3",
    notes: "note",
    // orginal url: "url",
    categories: ["Verbs"],
    status: "active",
  },
  {
    _id: 4,
    text: "word4",
    notes: "note",
    // orginal url: "url",
    categories: ["Cool Adjectives"],
    status: "active",
  },
  {
    _id: 5,
    text: "word5",
    notes: "note",
    // orginal url: "url",
    categories: ["Verbs"],
    status: "active",
  },
  {
    _id: 6,
    text: "word6",
    notes: "note",
    // orginal url: "url",
    categories: ["Inbox", "Verbs"],
    status: "active",
  },
  {
    _id: 7,
    text: "word7",
    notes: "note",
    // orginal url: "url",
    categories: ["Inbox", "Cool Adjectives", "New Words"],
    status: "active",
  },
  {
    _id: 8,
    text: "word8",
    notes: "note",
    // orginal url: "url",
    categories: ["Inbox"],
    status: "active",
  },
  {
    _id: 9,
    text: "word9",
    notes: "note",
    // orginal url: "url",
    categories: ["Inbox"],
    status: "deleted",
  },
];
