import { Word } from "../word";

type CLOSE_DIALOG = "CLOSE_DIALOG";
type OPEN_NEW_WORD_DIALOG = "OPEN_NEW_WORD_DIALOG";
type OPEN_UPDATE_WORD_DIALOG = "OPEN_UPDATE_WORD_DIALOG";

type actionType = {
  CLOSE_DIALOG: CLOSE_DIALOG;
  OPEN_NEW_WORD_DIALOG: OPEN_NEW_WORD_DIALOG;
  OPEN_UPDATE_WORD_DIALOG: OPEN_UPDATE_WORD_DIALOG;
};

export const DialogActions: actionType = {
  CLOSE_DIALOG: "CLOSE_DIALOG",
  OPEN_NEW_WORD_DIALOG: "OPEN_NEW_WORD_DIALOG",
  OPEN_UPDATE_WORD_DIALOG: "OPEN_UPDATE_WORD_DIALOG",
};

export type DialogAction =
  | { type: OPEN_NEW_WORD_DIALOG }
  | { type: OPEN_UPDATE_WORD_DIALOG; payload: Word }
  | { type: CLOSE_DIALOG };
